name: Build LaTeX document
on: [push]
      branches:
        - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo
        uses: actions/checkout@v3
        with:
          path: src
      

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/src:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -pdflatex $(basename $d_path)
            ) done
            cd src/glossario
            pdflatex glossario                        
            makeglossaries glossario                  
            pdflatex glossario                       
            pdflatex glossario
            '

      
