name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo
        uses: actions/checkout@v3
        with:
          path: src
      - name: Clone destination repo
        uses: actions/checkout@v3
        with:
          path: dst
          repository: Penta-Soft/docs
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/src:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -pdflatex $(basename $d_path)
            ) done
            cd src/glossario
            pdflatex glossario                        
            makeglossaries glossario                  
            pdflatex glossario                       
            pdflatex glossario
            '

      - name: upload pdf
        run: |
          shopt -s globstar
          set -e
          mv src/**/*.pdf dst
          cd dst
          for f in d_*; do mv "$f" $(echo "$f" | sed 's/^d_//g'); done
          mv AdR.pdf PdP.pdf PdQ.pdf ./esterni
          mv glossario.pdf NdP.pdf ./interni
          mv VE_* ./verbali/esterni
          mv VI_* ./verbali/interni
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "upload pdf"
          git push -u
